#pragma once

#ifndef VNLC_MEMBER_ACCESS_EXPRESSION_TYPE_HPP
#define VNLC_MEMBER_ACCESS_EXPRESSION_TYPE_HPP

enum class VnlcMemberAccessExpressionType {
    DOT,
    OPTIONAL_CHAINING,
};

#endif // VNLC_MEMBER_ACCESS_EXPRESSION_TYPE_HPP