#include "VnlcTokenTypeUtil.hpp"
#include <string_view>

std::string_view VnlcTokenTypeUtil::toString(VnlcTokenType type) {
    switch (type) {
        case VnlcTokenType::IDENTIFIER:
            return "VnlcTokenType::IDENTIFIER";
        case VnlcTokenType::NUMBER:
            return "VnlcTokenType::NUMBER";
        case VnlcTokenType::CHAR:
            return "VnlcTokenType::CHAR";
        case VnlcTokenType::STRING:
            return "VnlcTokenType::STRING";
        case VnlcTokenType::VAR:
            return "VnlcTokenType::VAR";
        case VnlcTokenType::LET:
            return "VnlcTokenType::LET";
        case VnlcTokenType::CONST:
            return "VnlcTokenType::CONST";
        case VnlcTokenType::FUNC:
            return "VnlcTokenType::FUNC";
        case VnlcTokenType::RETURN:
            return "VnlcTokenType::RETURN";
        case VnlcTokenType::IF:
            return "VnlcTokenType::IF";
        case VnlcTokenType::ELSE:
            return "VnlcTokenType::ELSE";
        case VnlcTokenType::FOR:
            return "VnlcTokenType::FOR";
        case VnlcTokenType::WHILE:
            return "VnlcTokenType::WHILE";
        case VnlcTokenType::LABEL:
            return "VnlcTokenType::LABEL";
        case VnlcTokenType::BREAK:
            return "VnlcTokenType::BREAK";
        case VnlcTokenType::CONTINUE:
            return "VnlcTokenType::CONTINUE";
        case VnlcTokenType::SWITCH:
            return "VnlcTokenType::SWITCH";
        case VnlcTokenType::CASE:
            return "VnlcTokenType::CASE";
        case VnlcTokenType::DEFAULT:
            return "VnlcTokenType::DEFAULT";
        case VnlcTokenType::WHEN:
            return "VnlcTokenType::WHEN";
        case VnlcTokenType::CONTEXT:
            return "VnlcTokenType::CONTEXT";
        case VnlcTokenType::VOID:
            return "VnlcTokenType::VOID";
        case VnlcTokenType::NATIVE:
            return "VnlcTokenType::NATIVE";
        case VnlcTokenType::CALLEE:
            return "VnlcTokenType::CALLEE";
        case VnlcTokenType::IN:
            return "VnlcTokenType::IN";
        case VnlcTokenType::RELOAD:
            return "VnlcTokenType::RELOAD";
        case VnlcTokenType::CLASS:
            return "VnlcTokenType::CLASS";
        case VnlcTokenType::INTERFACE:
            return "VnlcTokenType::INTERFACE";
        case VnlcTokenType::ABSTRACT:
            return "VnlcTokenType::ABSTRACT";
        case VnlcTokenType::TYPE:
            return "VnlcTokenType::TYPE";
        case VnlcTokenType::ENUM:
            return "VnlcTokenType::ENUM";
        case VnlcTokenType::RECORD:
            return "VnlcTokenType::RECORD";
        case VnlcTokenType::EXTENDS:
            return "VnlcTokenType::EXTENDS";
        case VnlcTokenType::IMPLEMENTS:
            return "VnlcTokenType::IMPLEMENTS";
        case VnlcTokenType::THIS:
            return "VnlcTokenType::THIS";
        case VnlcTokenType::SUPER:
            return "VnlcTokenType::SUPER";
        case VnlcTokenType::PRIVATE:
            return "VnlcTokenType::PRIVATE";
        case VnlcTokenType::PROTECTED:
            return "VnlcTokenType::PROTECTED";
        case VnlcTokenType::PUBLIC:
            return "VnlcTokenType::PUBLIC";
        case VnlcTokenType::READONLY:
            return "VnlcTokenType::READONLY";
        case VnlcTokenType::STATIC:
            return "VnlcTokenType::STATIC";
        case VnlcTokenType::INSTANCEOF:
            return "VnlcTokenType::INSTANCEOF";
        case VnlcTokenType::FINAL:
            return "VnlcTokenType::FINAL";
        case VnlcTokenType::OVERRIDE:
            return "VnlcTokenType::OVERRIDE";
        case VnlcTokenType::NONE:
            return "VnlcTokenType::NONE";
        case VnlcTokenType::TRUE:
            return "VnlcTokenType::TRUE";
        case VnlcTokenType::FALSE:
            return "VnlcTokenType::FALSE";
        case VnlcTokenType::IMPORT:
            return "VnlcTokenType::IMPORT";
        case VnlcTokenType::EXPORT:
            return "VnlcTokenType::EXPORT";
        case VnlcTokenType::AS:
            return "VnlcTokenType::AS";
        case VnlcTokenType::MODULE:
            return "VnlcTokenType::MODULE";
        case VnlcTokenType::PARENT:
            return "VnlcTokenType::PARENT";
        case VnlcTokenType::LAMBDA:
            return "VnlcTokenType::LAMBDA";
        case VnlcTokenType::COMMAND:
            return "VnlcTokenType::COMMAND";
        case VnlcTokenType::ASYNC:
            return "VnlcTokenType::ASYNC";
        case VnlcTokenType::AWAIT:
            return "VnlcTokenType::AWAIT";
        case VnlcTokenType::GENERATOR:
            return "VnlcTokenType::GENERATOR";
        case VnlcTokenType::YIELD:
            return "VnlcTokenType::YIELD";
        case VnlcTokenType::FROM:
            return "VnlcTokenType::FROM";
        case VnlcTokenType::DECORATOR:
            return "VnlcTokenType::DECORATOR";
        case VnlcTokenType::DECORATE:
            return "VnlcTokenType::DECORATE";
        case VnlcTokenType::TRY:
            return "VnlcTokenType::TRY";
        case VnlcTokenType::CATCH:
            return "VnlcTokenType::CATCH";
        case VnlcTokenType::FINALLY:
            return "VnlcTokenType::FINALLY";
        case VnlcTokenType::THROW:
            return "VnlcTokenType::THROW";
        case VnlcTokenType::PANIC:
            return "VnlcTokenType::PANIC";
        case VnlcTokenType::ASSERT:
            return "VnlcTokenType::ASSERT";
        case VnlcTokenType::TYPEOF:
            return "VnlcTokenType::TYPEOF";
        case VnlcTokenType::DEFER:
            return "VnlcTokenType::DEFER";
        case VnlcTokenType::ASSET:
            return "VnlcTokenType::ASSET";
        case VnlcTokenType::DEFINE:
            return "VnlcTokenType::DEFINE";
        case VnlcTokenType::METADATA:
            return "VnlcTokenType::METADATA";
        case VnlcTokenType::DEPRECATED:
            return "VnlcTokenType::DEPRECATED";
        case VnlcTokenType::EXPERIMENTAL:
            return "VnlcTokenType::EXPERIMENTAL";
        case VnlcTokenType::NOWARNINGS:
            return "VnlcTokenType::NOWARNINGS";
        case VnlcTokenType::GAMEVERSION:
            return "VnlcTokenType::GAMEVERSION";
        case VnlcTokenType::PLUS:
            return "VnlcTokenType::PLUS";
        case VnlcTokenType::MINUS:
            return "VnlcTokenType::MINUS";
        case VnlcTokenType::ASTERISK:
            return "VnlcTokenType::ASTERISK";
        case VnlcTokenType::SLASH:
            return "VnlcTokenType::SLASH";
        case VnlcTokenType::DOUBLE_SLASH:
            return "VnlcTokenType::DOUBLE_SLASH";
        case VnlcTokenType::PERCENT:
            return "VnlcTokenType::PERCENT";
        case VnlcTokenType::DOUBLE_ASTERISK:
            return "VnlcTokenType::DOUBLE_ASTERISK";
        case VnlcTokenType::PLUS_EQUAL:
            return "VnlcTokenType::PLUS_EQUAL";
        case VnlcTokenType::MINUS_EQUAL:
            return "VnlcTokenType::MINUS_EQUAL";
        case VnlcTokenType::ASTERISK_EQUAL:
            return "VnlcTokenType::ASTERISK_EQUAL";
        case VnlcTokenType::SLASH_EQUAL:
            return "VnlcTokenType::SLASH_EQUAL";
        case VnlcTokenType::DOUBLE_SLASH_EQUAL:
            return "VnlcTokenType::DOUBLE_SLASH_EQUAL";
        case VnlcTokenType::PERCENT_EQUAL:
            return "VnlcTokenType::PERCENT_EQUAL";
        case VnlcTokenType::DOUBLE_ASTERISK_EQUAL:
            return "VnlcTokenType::DOUBLE_ASTERISK_EQUAL";
        case VnlcTokenType::EQUAL:
            return "VnlcTokenType::EQUAL";
        case VnlcTokenType::DOUBLE_QUESTION_EQUAL:
            return "VnlcTokenType::DOUBLE_QUESTION_EQUAL";
        case VnlcTokenType::DOUBLE_EQUAL:
            return "VnlcTokenType::DOUBLE_EQUAL";
        case VnlcTokenType::EXCLAMATION_EQUAL:
            return "VnlcTokenType::EXCLAMATION_EQUAL";
        case VnlcTokenType::RIGHT_ANGLE:
            return "VnlcTokenType::RIGHT_ANGLE";
        case VnlcTokenType::RIGHT_ANGLE_EQUAL:
            return "VnlcTokenType::RIGHT_ANGLE_EQUAL";
        case VnlcTokenType::LEFT_ANGLE:
            return "VnlcTokenType::LEFT_ANGLE";
        case VnlcTokenType::LEFT_ANGLE_EQUAL:
            return "VnlcTokenType::LEFT_ANGLE_EQUAL";
        case VnlcTokenType::DOUBLE_AMPERSAND:
            return "VnlcTokenType::DOUBLE_AMPERSAND";
        case VnlcTokenType::DOUBLE_PIPE:
            return "VnlcTokenType::DOUBLE_PIPE";
        case VnlcTokenType::DOUBLE_QUESTION:
            return "VnlcTokenType::DOUBLE_QUESTION";
        case VnlcTokenType::EXCLAMATION:
            return "VnlcTokenType::EXCLAMATION";
        case VnlcTokenType::ARROW:
            return "VnlcTokenType::ARROW";
        case VnlcTokenType::AMPERSAND:
            return "VnlcTokenType::AMPERSAND";
        case VnlcTokenType::PIPE:
            return "VnlcTokenType::PIPE";
        case VnlcTokenType::CARET:
            return "VnlcTokenType::CARET";
        case VnlcTokenType::TILDE:
            return "VnlcTokenType::TILDE";
        case VnlcTokenType::DOUBLE_LEFT_ANGLE:
            return "VnlcTokenType::DOUBLE_LEFT_ANGLE";
        case VnlcTokenType::DOUBLE_RIGHT_ANGLE:
            return "VnlcTokenType::DOUBLE_RIGHT_ANGLE";
        case VnlcTokenType::TRIPLE_RIGHT_ANGLE:
            return "VnlcTokenType::TRIPLE_RIGHT_ANGLE";
        case VnlcTokenType::AMPERSAND_EQUAL:
            return "VnlcTokenType::AMPERSAND_EQUAL";
        case VnlcTokenType::PIPE_EQUAL:
            return "VnlcTokenType::PIPE_EQUAL";
        case VnlcTokenType::CARET_EQUAL:
            return "VnlcTokenType::CARET_EQUAL";
        case VnlcTokenType::DOUBLE_LEFT_ANGLE_EQUAL:
            return "VnlcTokenType::DOUBLE_LEFT_ANGLE_EQUAL";
        case VnlcTokenType::DOUBLE_RIGHT_ANGLE_EQUAL:
            return "VnlcTokenType::DOUBLE_RIGHT_ANGLE_EQUAL";
        case VnlcTokenType::TRIPLE_RIGHT_ANGLE_EQUAL:
            return "VnlcTokenType::TRIPLE_RIGHT_ANGLE_EQUAL";
        case VnlcTokenType::DOT:
            return "VnlcTokenType::DOT";
        case VnlcTokenType::COMMA:
            return "VnlcTokenType::COMMA";
        case VnlcTokenType::SEMICOLON:
            return "VnlcTokenType::SEMICOLON";
        case VnlcTokenType::COLON:
            return "VnlcTokenType::COLON";
        case VnlcTokenType::DOUBLE_COLON:
            return "VnlcTokenType::DOUBLE_COLON";
        case VnlcTokenType::QUESTION:
            return "VnlcTokenType::QUESTION";
        case VnlcTokenType::QUESTION_DOT:
            return "VnlcTokenType::QUESTION_DOT";
        case VnlcTokenType::EXCLAMATION_DOT:
            return "VnlcTokenType::EXCLAMATION_DOT";
        case VnlcTokenType::DOUBLE_DOT:
            return "VnlcTokenType::DOUBLE_DOT";
        case VnlcTokenType::TRIPLE_DOT:
            return "VnlcTokenType::TRIPLE_DOT";
        case VnlcTokenType::LEFT_PARENTHESIS:
            return "VnlcTokenType::LEFT_PARENTHESIS";
        case VnlcTokenType::RIGHT_PARENTHESIS:
            return "VnlcTokenType::RIGHT_PARENTHESIS";
        case VnlcTokenType::LEFT_BRACE:
            return "VnlcTokenType::LEFT_BRACE";
        case VnlcTokenType::RIGHT_BRACE:
            return "VnlcTokenType::RIGHT_BRACE";
        case VnlcTokenType::LEFT_BRACKET:
            return "VnlcTokenType::LEFT_BRACKET";
        case VnlcTokenType::RIGHT_BRACKET:
            return "VnlcTokenType::RIGHT_BRACKET";
        case VnlcTokenType::SELECTOR_PREFIX:
            return "VnlcTokenType::SELECTOR_PREFIX";
        case VnlcTokenType::INTERPOLATION_START:
            return "VnlcTokenType::INTERPOLATION_START";
        case VnlcTokenType::SINGLE_LINE_COMMENT:
            return "VnlcTokenType::SINGLE_LINE_COMMENT";
        case VnlcTokenType::MULTI_LINE_COMMENT:
            return "VnlcTokenType::MULTI_LINE_COMMENT";
        case VnlcTokenType::BLANK:
            return "VnlcTokenType::BLANK";
        case VnlcTokenType::NEWLINE:
            return "VnlcTokenType::NEWLINE";
        case VnlcTokenType::LEXICAL_ERROR:
            return "VnlcTokenType::LEXICAL_ERROR";
        case VnlcTokenType::END_OF_FILE:
            return "VnlcTokenType::END_OF_FILE";
        default:
            return "Unknown VnlcTokenType";
    }
}