#pragma once

#ifndef VNLC_FUNCTION_SIGNATURE_DECLARATION_PARSING_CONTEXT_HPP
#define VNLC_FUNCTION_SIGNATURE_DECLARATION_PARSING_CONTEXT_HPP

enum class VnlcFunctionSignatureDeclarationParsingContext {
    FUNCTION_SIGNATURE,
    METHOD_SIGNATURE,
};

#endif // VNLC_FUNCTION_SIGNATURE_DECLARATION_PARSING_CONTEXT_HPP