#pragma once

#ifndef VNLC_STRING_LITERAL_EXPRESSION_TYPE_HPP
#define VNLC_STRING_LITERAL_EXPRESSION_TYPE_HPP

enum class VnlcStringLiteralExpressionType {
    STRING,
    FORMAT_STRING,
    RAW_STRING,
};

#endif // VNLC_STRING_LITERAL_EXPRESSION_TYPE_HPP