#pragma once

#ifndef VNLC_LIST_LIKE_LITERAL_EXPRESSION_TYPE_HPP
#define VNLC_LIST_LIKE_LITERAL_EXPRESSION_TYPE_HPP

enum class VnlcListLikeLiteralExpressionType {
    LIST,

    BYTE_SNBT_ARRAY,
    INT_SNBT_ARRAY,
    LONG_SNBT_ARRAY,
};

#endif // VNLC_LIST_LIKE_LITERAL_EXPRESSION_TYPE_HPP