#pragma once

#ifndef VNLC_UNARY_EXPRESSION_TYPE_HPP
#define VNLC_UNARY_EXPRESSION_TYPE_HPP

enum class VnlcUnaryExpressionType {
    UNARY_PLUS,
    UNARY_MINUS,
    LOGICAL_NOT,
    BITWISE_NOT,
};

#endif // VNLC_UNARY_EXPRESSION_TYPE_HPP