#ifndef VNLC_SYMBOL_KIND_HPP
#define VNLC_SYMBOL_KIND_HPP

enum class VnlcSymbolKind {
    PACKAGE,
    MODULE,
    VARIABLE,
    FUNCTION,
    CLASS,
    INTERFACE,
    ENUM,
    TYPE_ALIAS,
    ENUM_MEMBER,
    PROPERTY,
    METHOD,
    PARAMETER,
    IMPORT_ALIAS,
    EXPORT_ALIAS,
};

#endif // VNLC_SYMBOL_KIND_HPP