#ifndef VNLC_REFERENCE_TYPE_KIND_HPP
#define VNLC_REFERENCE_TYPE_KIND_HPP

enum class VnlcReferenceTypeKind {
    CLASS,
    INTERFACE,
    ENUM,
    TYPE_ALIAS,
};

#endif // VNLC_REFERENCE_TYPE_KIND_HPP
