#ifndef VNLC_CUSTOMIZED_TYPE_KIND_HPP
#define VNLC_CUSTOMIZED_TYPE_KIND_HPP

enum class VnlcCustomizedTypeKind {
    CLASS,
    INTERFACE,
    ENUM,
    TYPE_ALIAS,
};

#endif // VNLC_CUSTOMIZED_TYPE_KIND_HPP
