#pragma once

#ifndef VNLC_PARSING_RESULTS_HPP
#define VNLC_PARSING_RESULTS_HPP

#include "VnlcAbsoluteImportPathItemParsingResult.hpp"       // IWYU pragma: export
#include "VnlcAbsoluteImportPathListParsingResult.hpp"       // IWYU pragma: export
#include "VnlcAbsoluteImportPathParsingResult.hpp"           // IWYU pragma: export
#include "VnlcAdditiveExpressionParsingResult.hpp"           // IWYU pragma: export
#include "VnlcArgumentListParsingResult.hpp"                 // IWYU pragma: export
#include "VnlcAssignmentExpressionParsingResult.hpp"         // IWYU pragma: export
#include "VnlcBitwiseAndExpressionParsingResult.hpp"         // IWYU pragma: export
#include "VnlcBitwiseOrExpressionParsingResult.hpp"          // IWYU pragma: export
#include "VnlcBitwiseXorExpressionParsingResult.hpp"         // IWYU pragma: export
#include "VnlcBlockStatementParsingResult.hpp"               // IWYU pragma: export
#include "VnlcBooleanParsingResult.hpp"                      // IWYU pragma: export
#include "VnlcBreakStatementParsingResult.hpp"               // IWYU pragma: export
#include "VnlcClassBodyParsingResult.hpp"                    // IWYU pragma: export
#include "VnlcClassDeclarationParsingResult.hpp"             // IWYU pragma: export
#include "VnlcClassMemberParsingResult.hpp"                  // IWYU pragma: export
#include "VnlcConditionalExpressionParsingResult.hpp"        // IWYU pragma: export
#include "VnlcContinueStatementParsingResult.hpp"            // IWYU pragma: export
#include "VnlcControlFlowStatementParsingResult.hpp"         // IWYU pragma: export
#include "VnlcDictEntryParsingResult.hpp"                    // IWYU pragma: export
#include "VnlcDictLiteralParsingResult.hpp"                  // IWYU pragma: export
#include "VnlcEnumAssociatedValueListParsingResult.hpp"      // IWYU pragma: export
#include "VnlcEnumAssociatedValueParsingResult.hpp"          // IWYU pragma: export
#include "VnlcEnumBodyParsingResult.hpp"                     // IWYU pragma: export
#include "VnlcEnumDeclarationParsingResult.hpp"              // IWYU pragma: export
#include "VnlcEnumMemberDeclarationParsingResult.hpp"        // IWYU pragma: export
#include "VnlcEqualityExpressionParsingResult.hpp"           // IWYU pragma: export
#include "VnlcExponentialExpressionParsingResult.hpp"        // IWYU pragma: export
#include "VnlcExportDeclarationParsingResult.hpp"            // IWYU pragma: export
#include "VnlcExportListParsingResult.hpp"                   // IWYU pragma: export
#include "VnlcExpressionParsingResult.hpp"                   // IWYU pragma: export
#include "VnlcExpressionStatementParsingResult.hpp"          // IWYU pragma: export
#include "VnlcForStatementParsingResult.hpp"                 // IWYU pragma: export
#include "VnlcFunctionBodyParsingResult.hpp"                 // IWYU pragma: export
#include "VnlcFunctionDeclarationParsingResult.hpp"          // IWYU pragma: export
#include "VnlcFunctionSignatureParsingResult.hpp"            // IWYU pragma: export
#include "VnlcGenericArgumentListParsingResult.hpp"          // IWYU pragma: export
#include "VnlcGenericParameterListParsingResult.hpp"         // IWYU pragma: export
#include "VnlcIfStatementParsingResult.hpp"                  // IWYU pragma: export
#include "VnlcImportDeclarationParsingResult.hpp"            // IWYU pragma: export
#include "VnlcImportPathParsingResult.hpp"                   // IWYU pragma: export
#include "VnlcInterfaceBodyParsingResult.hpp"                // IWYU pragma: export
#include "VnlcInterfaceDeclarationParsingResult.hpp"         // IWYU pragma: export
#include "VnlcInterfaceMethodDeclarationParsingResult.hpp"   // IWYU pragma: export
#include "VnlcInterpolationParsingResult.hpp"                // IWYU pragma: export
#include "VnlcListLiteralParsingResult.hpp"                  // IWYU pragma: export
#include "VnlcLiteralParsingResult.hpp"                      // IWYU pragma: export
#include "VnlcLogicalAndExpressionParsingResult.hpp"         // IWYU pragma: export
#include "VnlcLogicalOrExpressionParsingResult.hpp"          // IWYU pragma: export
#include "VnlcMetadataParsingResult.hpp"                     // IWYU pragma: export
#include "VnlcMetadataTermParsingResult.hpp"                 // IWYU pragma: export
#include "VnlcModuleParsingResult.hpp"                       // IWYU pragma: export
#include "VnlcMultiplicativeExpressionParsingResult.hpp"     // IWYU pragma: export
#include "VnlcNativeFunctionDeclarationParsingResult.hpp"    // IWYU pragma: export
#include "VnlcNullishCoalescingExpressionParsingResult.hpp"  // IWYU pragma: export
#include "VnlcParameterListParsingResult.hpp"                // IWYU pragma: export
#include "VnlcParameterParsingResult.hpp"                    // IWYU pragma: export
#include "VnlcPostfixExpressionParsingResult.hpp"            // IWYU pragma: export
#include "VnlcPostfixSuffixParsingResult.hpp"                // IWYU pragma: export
#include "VnlcPrimaryExpressionParsingResult.hpp"            // IWYU pragma: export
#include "VnlcPropertyDeclarationParsingResult.hpp"          // IWYU pragma: export
#include "VnlcRangeExpressionParsingResult.hpp"              // IWYU pragma: export
#include "VnlcRegularFunctionDeclarationParsingResult.hpp"   // IWYU pragma: export
#include "VnlcRelationalExpressionParsingResult.hpp"         // IWYU pragma: export
#include "VnlcRelativeImportPathItemParsingResult.hpp"       // IWYU pragma: export
#include "VnlcRelativeImportPathListParsingResult.hpp"       // IWYU pragma: export
#include "VnlcRelativeImportPathParsingResult.hpp"           // IWYU pragma: export
#include "VnlcReloadStatementParsingResult.hpp"              // IWYU pragma: export
#include "VnlcReturnStatementParsingResult.hpp"              // IWYU pragma: export
#include "VnlcSNBTArrayParsingResult.hpp"                    // IWYU pragma: export
#include "VnlcSelectorArgumentListParsingResult.hpp"         // IWYU pragma: export
#include "VnlcSelectorArgumentParsingResult.hpp"             // IWYU pragma: export
#include "VnlcSelectorParsingResult.hpp"                     // IWYU pragma: export
#include "VnlcShiftExpressionParsingResult.hpp"              // IWYU pragma: export
#include "VnlcStatementParsingResult.hpp"                    // IWYU pragma: export
#include "VnlcStringParsingResult.hpp"                       // IWYU pragma: export
#include "VnlcStringPartParsingResult.hpp"                   // IWYU pragma: export
#include "VnlcSwitchCaseParsingResult.hpp"                   // IWYU pragma: export
#include "VnlcSwitchStatementParsingResult.hpp"              // IWYU pragma: export
#include "VnlcTopIdentifierDeclarationParsingResult.hpp"     // IWYU pragma: export
#include "VnlcTypeAliasDeclarationParsingResult.hpp"         // IWYU pragma: export
#include "VnlcTypeAnnotationParsingResult.hpp"               // IWYU pragma: export
#include "VnlcTypeDeclarationParsingResult.hpp"              // IWYU pragma: export
#include "VnlcTypeParsingResult.hpp"                         // IWYU pragma: export
#include "VnlcUnaryExpressionParsingResult.hpp"              // IWYU pragma: export
#include "VnlcVariableDeclarationParsingResult.hpp"          // IWYU pragma: export
#include "VnlcVariableDeclarationPrimaryParsingResult.hpp"   // IWYU pragma: export
#include "VnlcVariableDeclarationStatementParsingResult.hpp" // IWYU pragma: export
#include "VnlcWhileStatementParsingResult.hpp"               // IWYU pragma: export

#endif // VNLC_PARSING_RESULTS_HPP